site:
  name: TaxiTitan
  site: 'https://taxititan.ro'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: TaxiTitan
    template: '%s — TaxiTitan'
  description: 'Servicii de taxi rapide si sigure.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: TaxiTitan
    type: website

i18n:
  language: ro
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
